name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install goreleaser
        run: go install github.com/goreleaser/goreleaser@latest
      - name: Run goreleaser
        run: goreleaser release --rm-dist